### PR TITLE
Close db migration

### LINKED ISSUE #54: Close db in Migration function
The `database.Migration` function https://github.com/src-d/metadata-retrieval/blob/master/database/database.go is not closing the connection with the db, so if you try to modify that database from other place you get an error:
```
        	Error:      	Received unexpected error:
        	            	pq: database "testing5205599535230193171" is being accessed by other users

```

(We are getting those errors trying to drop the test databases after they pass)

https://github.com/src-d/data-retrieval/blob/master/dbstore/model/sql.go#L290-L314 This how we are doing migration in src-d/data-retrieval

### PR DESCRIPTION
**Pull request by smacker**
Fix: #54

Signed-off-by: Maxim Sukharev <max@smacker.ru>

---

* [ ] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [x] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

File: database/database.go [hunk 1]
```diff
@@ -22,5 +22,11 @@ func Migrate(databaseURL string) error {
 	if err != nil {
 		return err
 	}
-	return m.Up()
+
+	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
+		return err
+	}
+
+	_, err = m.Close()
```
Comment (se7entyse7en) [inline database/database.go]: Shouldn't this be in a `defer`?

Comment (smacker) [reply database/database.go]: it doesn't really matter in this case as failed migration would mean the program will have to exit. There is no way it will be able to do anything with incorrect migration.
so it's just simpler to write like this than making named return with defer.

if you really want to change just to make it "completely right" let me know, I'll update the pr.

Comment (se7entyse7en) [reply database/database.go]: no, it's fine 👍

**Review by se7entyse7en — APPROVED** [review]
